// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PruebaTecnicaBank.Infrastructure.Context;

#nullable disable

namespace PruebaTecnicaBank.Infrastructure.Migrations
{
    [DbContext(typeof(BankDbContext))]
    partial class BankDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("PruebaTecnicaBank.Core.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("TEXT")
                        .HasColumnName("BirthDate");

                    b.Property<decimal>("Ingresos")
                        .HasColumnType("TEXT")
                        .HasColumnName("Income");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<int>("Sexo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Sex");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("PruebaTecnicaBank.Core.Entities.Cuenta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("TEXT")
                        .HasColumnName("ClientId");

                    b.Property<string>("NumeroCuenta")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("AccountNumber");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("TEXT")
                        .HasColumnName("Balance");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("NumeroCuenta")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("PruebaTecnicaBank.Core.Entities.Transaccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CuentaId")
                        .HasColumnType("TEXT")
                        .HasColumnName("AccountId");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("TEXT")
                        .HasColumnName("Timestamp");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT")
                        .HasColumnName("Amount");

                    b.Property<decimal>("SaldoDespues")
                        .HasColumnType("TEXT")
                        .HasColumnName("BalanceAfter");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Type");

                    b.HasKey("Id");

                    b.HasIndex("CuentaId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("PruebaTecnicaBank.Core.Entities.Cuenta", b =>
                {
                    b.HasOne("PruebaTecnicaBank.Core.Entities.Cliente", "Cliente")
                        .WithMany("Cuentas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("PruebaTecnicaBank.Core.Entities.Transaccion", b =>
                {
                    b.HasOne("PruebaTecnicaBank.Core.Entities.Cuenta", "Cuenta")
                        .WithMany("Transacciones")
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("PruebaTecnicaBank.Core.Entities.Cliente", b =>
                {
                    b.Navigation("Cuentas");
                });

            modelBuilder.Entity("PruebaTecnicaBank.Core.Entities.Cuenta", b =>
                {
                    b.Navigation("Transacciones");
                });
#pragma warning restore 612, 618
        }
    }
}
